name = "open-lovable4"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "open-lovable4"
workers_dev = false

[env.staging]
name = "open-lovable4-staging"
workers_dev = true

# إعدادات Pages
[pages]
name = "open-lovable4"